development:
  adapter: postgis
  encoding: unicode
  database: toukraine_development
  template: template_toukraine
  host: localhost
  pool: 5
  username: postgres
  script_dir: /usr/local/share/postgis

test: &test
  adapter: postgis
  encoding: unicode
  database: toukraine_test
  template: template_toukraine
  pool: 5
  username: postgres
  script_dir: /usr/local/share/postgis

production:
  adapter: postgis
  encoding: unicode
  database: toukraine_production
  template: template_toukraine
  pool: 5
  username: postgres

staging:
  adapter: postgis
  encoding: unicode
  database: toukraine_staging
  template: template_toukraine
  pool: 5
  username: postgres

cucumber:
  <<: *test