development:
  adapter: postgresql
  database: toukraine_dev
  username: postgres

production:
  adapter: postgresql
  database: toukraine_prod
  username: postgres

test: &test
  adapter: postgresql
  database: toukraine_test
  username: postgres
cucumber:
  <<: *test